/**
 * CSV helpers for Nilai Akhlak import/export.
 *
 * Template format:
 *   nomor_induk,nama_santri,nilai_angka,deskripsi
 */

export interface CsvAkhlakRow {
  nomor_induk: string
  nama_santri: string
  nilai_angka: string
  deskripsi: string
}

export interface CsvAkhlakParseResult {
  rows: CsvAkhlakRow[]
  errors: { line: number; message: string }[]
}

// ---------------------------------------------------------------------------
// Download
// ---------------------------------------------------------------------------

/**
 * Generate and trigger download of a pre-filled CSV template for Nilai Akhlak.
 *
 * @param santris   Existing santri rows (from the form state)
 * @param meta  Metadata for the filename
 */
export function downloadAkhlakTemplate(
  santris: CsvAkhlakRow[],
  meta: { kodeKelas: string; aspek: string; tahunAjaran: string; semester: string },
): void {
  const header = ["nomor_induk", "nama_santri", "nilai_angka", "deskripsi"]

  const rows = santris.map((s) => [s.nomor_induk, s.nama_santri, s.nilai_angka, s.deskripsi])

  const csvLines = [header, ...rows].map((row) =>
    row.map((cell) => {
      const str = String(cell ?? "")
      // Quote cells that contain comma, newline, or double quote
      if (str.includes(",") || str.includes("\n") || str.includes('"')) {
        return `"${str.replace(/"/g, '""')}"`
      }
      return str
    }).join(","),
  )

  const csvContent = csvLines.join("\r\n")
  const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement("a")
  const safeTahun = meta.tahunAjaran.replace(/\//g, "-")
  const safeAspek = meta.aspek.replace(/[^a-zA-Z0-9]/g, "_")
  anchor.href = url
  anchor.download = `akhlak-${meta.kodeKelas}-${safeAspek}-${safeTahun}-s${meta.semester}.csv`
  anchor.click()
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Upload / Parse
// ---------------------------------------------------------------------------

/**
 * Parse a CSV file previously generated by `downloadAkhlakTemplate`.
 * Returns structured rows plus any per-row validation errors.
 */
export async function parseAkhlakCsv(file: File): Promise<CsvAkhlakParseResult> {
  const text = await file.text()
  // Strip BOM if present
  const content = text.startsWith("\uFEFF") ? text.slice(1) : text

  const lines = content.split(/\r?\n/).filter((l) => l.trim() !== "")
  if (lines.length < 2) {
    return {
      rows: [],
      errors: [{ line: 0, message: "File CSV kosong atau tidak memiliki data." }],
    }
  }

  const parseCsvLine = (line: string): string[] => {
    const result: string[] = []
    let current = ""
    let inQuotes = false
    for (let i = 0; i < line.length; i++) {
      const char = line[i]
      if (char === '"') {
        if (inQuotes && line[i + 1] === '"') {
          current += '"'
          i++
        } else {
          inQuotes = !inQuotes
        }
      } else if (char === "," && !inQuotes) {
        result.push(current)
        current = ""
      } else {
        current += char
      }
    }
    result.push(current)
    return result
  }

  const headerCols = parseCsvLine(lines[0]).map((h) => h.trim().toUpperCase())

  // Detect column positions
  const idxNomorInduk = headerCols.indexOf("NOMOR_INDUK")
  if (idxNomorInduk === -1) {
    return {
      rows: [],
      errors: [{ line: 1, message: "Header 'nomor_induk' tidak ditemukan di baris pertama." }],
    }
  }

  const idxNilaiAngka = headerCols.indexOf("NILAI_ANGKA")
  const idxDeskripsi = headerCols.indexOf("DESKRIPSI")

  const rows: CsvAkhlakRow[] = []
  const errors: { line: number; message: string }[] = []

  for (let i = 1; i < lines.length; i++) {
    const lineNum = i + 1
    const cols = parseCsvLine(lines[i])
    const nomorInduk = cols[idxNomorInduk]?.trim() ?? ""

    if (!nomorInduk) {
      errors.push({ line: lineNum, message: "nomor_induk kosong, baris dilewati." })
      continue
    }

    const namaSantri = cols[1]?.trim() ?? ""
    const nilaiAngkaRaw = idxNilaiAngka !== -1 ? cols[idxNilaiAngka]?.trim() ?? "" : ""
    
    if (nilaiAngkaRaw !== "") {
      const n = Number(nilaiAngkaRaw)
      if (isNaN(n) || n < 0 || n > 100) {
        errors.push({ line: lineNum, message: `Nilai angka tidak valid (${nilaiAngkaRaw}). Harus antara 0 dan 100.` })
      }
    }

    const deskripsiRaw = idxDeskripsi !== -1 ? cols[idxDeskripsi]?.trim() ?? "" : ""

    rows.push({
      nomor_induk: nomorInduk,
      nama_santri: namaSantri,
      nilai_angka: nilaiAngkaRaw,
      deskripsi: deskripsiRaw,
    })
  }

  return { rows, errors }
}
