/**
 * CSV helpers for Nilai Mapel import/export.
 *
 * Template format (per-mapel):
 *   nomor_induk,nama_santri,T1,T2,...,Tn,UH1,UH2,...,UHm,UAS
 *
 * All UH values are assumed valid (soal_disusun_pengajar=true, diawasi_pengajar=true).
 */

export interface CsvSantriRow {
  nomor_induk: string
  nama_santri: string
  tugas: string[]
  ulangan: string[]
  uas: string
  keterangan: string
}

export interface CsvParseResult {
  rows: CsvSantriRow[]
  errors: { line: number; message: string }[]
  tugasCount: number
  ulanganCount: number
}

// ---------------------------------------------------------------------------
// Download
// ---------------------------------------------------------------------------

/**
 * Generate and trigger download of a pre-filled CSV template.
 *
 * @param santris   Existing santri rows (from the form state)
 * @param tugasCount  Number of tugas columns
 * @param ulanganCount  Number of ulangan columns
 * @param meta  Metadata for the filename
 */
export function downloadNilaiTemplate(
  santris: CsvSantriRow[],
  tugasCount: number,
  ulanganCount: number,
  meta: { kodeKelas: string; kodeMapel: string; tahunAjaran: string; semester: string },
): void {
  const tugasHeaders = Array.from({ length: tugasCount }, (_, i) => `T${i + 1}`)
  const ulanganHeaders = Array.from({ length: ulanganCount }, (_, i) => `UH${i + 1}`)

  const header = ["nomor_induk", "nama_santri", ...tugasHeaders, ...ulanganHeaders, "UAS", "KETERANGAN"]

  const rows = santris.map((s) => {
    const tugas = Array.from({ length: tugasCount }, (_, i) => s.tugas[i] ?? "")
    const ulangan = Array.from({ length: ulanganCount }, (_, i) => s.ulangan[i] ?? "")
    return [s.nomor_induk, s.nama_santri, ...tugas, ...ulangan, s.uas, s.keterangan]
  })

  const csvLines = [header, ...rows].map((row) =>
    row.map((cell) => {
      const str = String(cell ?? "")
      // Quote cells that contain comma, newline, or double quote
      if (str.includes(",") || str.includes("\n") || str.includes('"')) {
        return `"${str.replace(/"/g, '""')}"`
      }
      return str
    }).join(","),
  )

  const csvContent = csvLines.join("\r\n")
  const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement("a")
  const safeTahun = meta.tahunAjaran.replace(/\//g, "-")
  anchor.href = url
  anchor.download = `nilai-${meta.kodeKelas}-${meta.kodeMapel}-${safeTahun}-s${meta.semester}.csv`
  anchor.click()
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Upload / Parse
// ---------------------------------------------------------------------------

/**
 * Parse a CSV file previously generated by `downloadNilaiTemplate`.
 * Returns structured rows plus any per-row validation errors.
 */
export async function parseNilaiCsv(file: File): Promise<CsvParseResult> {
  const text = await file.text()
  // Strip BOM if present
  const content = text.startsWith("\uFEFF") ? text.slice(1) : text

  const lines = content.split(/\r?\n/).filter((l) => l.trim() !== "")
  if (lines.length < 2) {
    return {
      rows: [],
      errors: [{ line: 0, message: "File CSV kosong atau tidak memiliki data." }],
      tugasCount: 0,
      ulanganCount: 0,
    }
  }

  const parseCsvLine = (line: string): string[] => {
    const result: string[] = []
    let current = ""
    let inQuotes = false
    for (let i = 0; i < line.length; i++) {
      const char = line[i]
      if (char === '"') {
        if (inQuotes && line[i + 1] === '"') {
          current += '"'
          i++
        } else {
          inQuotes = !inQuotes
        }
      } else if (char === "," && !inQuotes) {
        result.push(current)
        current = ""
      } else {
        current += char
      }
    }
    result.push(current)
    return result
  }

  const headerCols = parseCsvLine(lines[0]).map((h) => h.trim().toUpperCase())

  // Detect column positions
  const idxNomorInduk = headerCols.indexOf("NOMOR_INDUK")
  if (idxNomorInduk === -1) {
    return {
      rows: [],
      errors: [{ line: 1, message: "Header 'nomor_induk' tidak ditemukan di baris pertama." }],
      tugasCount: 0,
      ulanganCount: 0,
    }
  }

  const tugasIndexes: number[] = []
  const ulanganIndexes: number[] = []
  let uasIndex = -1
  let keteranganIndex = -1

  for (let col = 0; col < headerCols.length; col++) {
    const h = headerCols[col]
    if (/^T\d+$/.test(h)) tugasIndexes.push(col)
    else if (/^UH\d+$/.test(h)) ulanganIndexes.push(col)
    else if (h === "UAS") uasIndex = col
    else if (h === "KETERANGAN") keteranganIndex = col
  }

  const tugasCount = tugasIndexes.length
  const ulanganCount = ulanganIndexes.length

  const rows: CsvSantriRow[] = []
  const errors: { line: number; message: string }[] = []

  for (let i = 1; i < lines.length; i++) {
    const lineNum = i + 1
    const cols = parseCsvLine(lines[i])
    const nomorInduk = cols[idxNomorInduk]?.trim() ?? ""

    if (!nomorInduk) {
      errors.push({ line: lineNum, message: "nomor_induk kosong, baris dilewati." })
      continue
    }

    const namaSantri = cols[1]?.trim() ?? ""

    const tugas = tugasIndexes.map((ci) => {
      const raw = cols[ci]?.trim() ?? ""
      const n = Number(raw)
      if (raw !== "" && (isNaN(n) || n < 0 || n > 100)) {
        errors.push({ line: lineNum, message: `Nilai tugas kolom ${headerCols[ci]} tidak valid (${raw}).` })
      }
      return raw
    })

    const ulangan = ulanganIndexes.map((ci) => {
      const raw = cols[ci]?.trim() ?? ""
      const n = Number(raw)
      if (raw !== "" && (isNaN(n) || n < 0 || n > 100)) {
        errors.push({ line: lineNum, message: `Nilai ulangan kolom ${headerCols[ci]} tidak valid (${raw}).` })
      }
      return raw
    })

    const uasRaw = uasIndex !== -1 ? cols[uasIndex]?.trim() ?? "" : ""
    if (uasRaw !== "") {
      const n = Number(uasRaw)
      if (isNaN(n) || n < 0 || n > 100) {
        errors.push({ line: lineNum, message: `Nilai UAS tidak valid (${uasRaw}).` })
      }
    }

    const keteranganRaw = keteranganIndex !== -1 ? cols[keteranganIndex]?.trim() ?? "" : ""

    rows.push({ nomor_induk: nomorInduk, nama_santri: namaSantri, tugas, ulangan, uas: uasRaw, keterangan: keteranganRaw })
  }

  return { rows, errors, tugasCount, ulanganCount }
}
